<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DbContexts\AppDbContext\DiaAdminDbContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.7" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Syncfusion.Pdf.Imaging.Net.Core" Version="24.1.41" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="24.1.41" />
    <PackageReference Include="Syncfusion.PdfToImageConverter.Net" Version="24.1.41" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.5" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="DbContexts\AppDbContext\" />
    <Folder Include="SQL script\" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Framework\FrameworkCore\FrameworkCore.csproj" />
  </ItemGroup>



</Project>
